// user = "Bookpurchase";
// password = "rJz154fVoWtjzQfD"
const MONGO_CONN_URL = "mongodb+srv://Bookpurchase:rJz154fVoWtjzQfD@cluster0.rn8qnzf.mongodb.net/FYP-Database?retryWrites=true&w=majority";
const USER_COLLECTION = "users";
const PRODUCT_COLLECTION = "products";
const REQUEST_COLLECTION = "request";
const REVIEW_COLLECTION = "review";
const SHOP_COLLECTION = "Shops";
const SHOP_PRODUCTS_COLLECTION = "shopproducts";
const CART_COLLECTION = "Cart";
const ORDER_COLLECTION = "order";
const BORROW_COLLECTION = "borrowproduct";
const BORROW_REQUEST_COLLECTION = "borrowrequest";
const DISCOUNT_VOUCHER_COLLECTION = "discount";
const RIDER_COLLECTION = "Rider";
const ORDER_REQUESTS_TAKEN_BY_RIDER_COLLECTION = "ordersrequesttaken";